import json
import os
import sys
import uuid
from datetime import datetime, timezone

import requests
from dotenv import load_dotenv

from auth import get_management_token

load_dotenv()

API_VERSION = "2025-09-01"

SUBSCRIPTION_ID = os.environ.get("AZURE_SUBSCRIPTION_ID")
RESOURCE_GROUP = os.environ.get("AZURE_RESOURCE_GROUP")
WORKSPACE_NAME = os.environ.get("SENTINEL_WORKSPACE_NAME")


def _incidents_url() -> str:
    return (
        f"https://management.azure.com/subscriptions/{SUBSCRIPTION_ID}"
        f"/resourceGroups/{RESOURCE_GROUP}"
        f"/providers/Microsoft.OperationalInsights/workspaces/{WORKSPACE_NAME}"
        f"/providers/Microsoft.SecurityInsights/incidents"
    )


def render_comment(triage: dict, incident_meta: dict) -> str:
    """Render a triage.py output as the markdown comment it would post to a
    Sentinel incident. Always prefixed as automated/unverified - this is a
    draft for a human analyst, never a determination (see rule 4 in
    prompts/triage_system.md)."""
    props = incident_meta["properties"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("> \U0001f916 **Automated AI Triage \u2014 Unverified**")
    lines.append(
        "> Generated by `triage.py` (Claude Sonnet 5) at "
        f"{generated_at}. This is a draft assessment for human review, not a "
        "confirmed determination. Verify every cited event before acting on any "
        "recommendation below."
    )
    lines.append("")
    lines.append(
        f"*Incident #{props['incidentNumber']} \u00b7 {props['title']} \u00b7 "
        f"Severity: {props['severity']} \u00b7 Status: {props['status']}*"
    )
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(triage["summary"])
    lines.append("")

    lines.append("## Attack Narrative")
    lines.append("")
    lines.append("| Time (UTC) | Step |")
    lines.append("|---|---|")
    for step in triage["attack_narrative"]:
        step_text = step["step"].replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {step['time']} | {step_text} |")
    lines.append("")

    lines.append("## MITRE ATT&CK Techniques")
    lines.append("")
    lines.append("| Technique | Tactic | Confidence | Evidence |")
    lines.append("|---|---|---|---|")
    for tech in triage["mitre_techniques"]:
        evidence = "; ".join(tech["evidence"]).replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {tech['technique_id']} ({tech['technique_name']}) | {tech['tactic']} | "
            f"{tech['confidence']} | {evidence} |"
        )
    lines.append("")

    lines.append("## Suggested Verdict")
    lines.append("")
    lines.append(f"**{triage['suggested_verdict']}**")
    lines.append("")

    lines.append("## Recommended Actions")
    lines.append("")
    for action in triage["recommended_actions"]:
        lines.append(f"- {action}")
    lines.append("")

    lines.append("## Needs Human Verification")
    lines.append("")
    for item in triage["verification_needed"]:
        lines.append(f"- {item}")
    lines.append("")

    return "\n".join(lines)


def save_comment(incident_number: int, comment_md: str) -> str:
    os.makedirs("output", exist_ok=True)
    path = f"output/incident-{incident_number}-comment.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(comment_md)
    return path


def post_comment_live(incident_name: str, comment_md: str) -> dict:
    """PUT the rendered comment to the live Sentinel incident. Not called
    unless --live is explicitly passed - Azure's subscription is currently
    suspended, so this path is untested against a real workspace."""
    token = get_management_token()
    comment_id = str(uuid.uuid4())
    url = f"{_incidents_url()}/{incident_name}/comments/{comment_id}?api-version={API_VERSION}"
    response = requests.put(
        url,
        headers={"Authorization": f"Bearer {token}"},
        json={"properties": {"message": comment_md}},
    )
    response.raise_for_status()
    return response.json()


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--live"]
    live = "--live" in sys.argv[1:]

    if not args:
        print("Usage: python src/writeback.py <incident_number> [--live]")
        sys.exit(1)

    incident_number = int(args[0])

    with open(f"samples/incident-{incident_number}-triage.json", encoding="utf-8") as f:
        triage = json.load(f)
    with open(f"samples/incident-{incident_number}.json", encoding="utf-8") as f:
        incident_meta = json.load(f)["incident"]

    comment_md = render_comment(triage, incident_meta)
    path = save_comment(incident_number, comment_md)
    print(f"Saved {path}")

    if live:
        incident_name = incident_meta["name"]
        result = post_comment_live(incident_name, comment_md)
        print(f"Posted live comment to incident #{incident_number}: {result.get('name')}")
    else:
        print("Live PUT skipped (pass --live to post to the Sentinel incident).")
